### PR TITLE
Combine Invesalius Sphinx documentation with invesalius.github.io

### PR DESCRIPTION
**Pull request by ilona-m**
Steps to compile sphinx documentation on Local:
1. Go to 'edit_documentation_here'.
2. Install required packages from requirements.txt.
3. Use MakeFile to run ´make html´.
4. Find 'documentation_preview' in root folder.

Workflow for github hosting:
(.github/worflows/jekyll.yml)
1. Push changes to repository.
2. Github Action runs jekyll.yml
3. Sphinx documentation is built on the server.
4. Changes are pushed automatically to the repository.
5. Jekyll is compiled.
6. Website is deployed to invesalius.github.io

### CODE REVIEW

**Comment by tfmoraes** [comment]
Hi @ilona-m. It looks very good! But there is some problems:

1. Images are not numbered
2. References to images are not numbered
3. Some warnings with cross-reference

I did some modifications and fixed all 3 problems. I created a patch with the modifications https://gist.github.com/tfmoraes/7838d0d6c4fa704bb1598261ee724f1e . The main modifications in this patch are:

1. Added `numfig = True` to add numbers to the images
2. Referencing images this way ```{numref}`text_on````
3. I fixed all the warning except one, the cross-reference to a neuronaviagtion section.

**Comment by ilona-m** [comment]
> Hi @ilona-m. It looks very good! But there is some problems:
> 
> 1. Images are not numbered
> 2. References to images are not numbered
> 3. Some warnings with cross-reference
> 
> I did some modifications and fixed all 3 problems. I created a patch with the modifications https://gist.github.com/tfmoraes/7838d0d6c4fa704bb1598261ee724f1e . The main modifications in this patch are:
> 
> 1. Added `numfig = True` to add numbers to the images
> 2. Referencing images this way ```{numref}`text_on````
> 3. I fixed all the warning except one, the cross-reference to a neuronaviagtion section.

Hi @tfmoraes , thank you for the fixes! I added the patch and removed the cross-reference to neuronavigation for now. The chapter will be published later, but it might go under a different section.

**Comment by tfmoraes** [comment]
Hi @ilona-m, `pydata-sphinx-theme` is missing in `requirements.txt`.

**Comment by tfmoraes** [comment]
Those `.idea` folder are from intellij? Try to remove that from this PR.

**Comment by ilona-m** [comment]
Hi @tfmoraes , I changed the correct theme to the requirements file and added .idea files to the gitignore file.

**Comment by tfmoraes** [comment]
Thanks @ilona-m. Merging it!

**Pull request merged**
